version: '3.2'

volumes:
  pg-data:
    driver: local

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=jekakrut
      - POSTGRES_USER=jeka
      - POSTGRES_PASSWORD=krut
    restart: always

  app:
    build: .
    command: uvicorn src.main:app --reload --reload-dir /opt/src --host 0.0.0.0 --port 8001
    ports:
      - '8001:8001'
    volumes:
      - ./src:/opt/src
    restart: always